# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'AzureRmPipeline-conn'
    subscriptionName: '540c8825-d068-4e5a-92ad-c23246ccad9e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'EastUS'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateAzureStorage/azuredeploy.json'
    deploymentMode: 'Incremental'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
